apiVersion: batch/v1
kind: CronJob
metadata:
  name: go-demo-app-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: go-demo-app-cronjob
            image: busybox
            command:
            - /bin/sh
            - -c
            - echo "Hello from the cron job"
          restartPolicy: OnFailure
