apiVersion: v1
kind: Secret
metadata:
  name: go-demo-app-secret
type: Opaque
data:
  MY_SECRET: bXlzZWNyZXR2YWx1ZQ== # mysecretvalue
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-demo-app
  template:
    metadata:
      labels:
        app: go-demo-app
    spec:
      containers:
      - name: go-demo-app
        image: denvasyliev/go-demo-app:v1.0.0
        env:
        - name: MY_SECRET_ENV
          valueFrom:
            secretKeyRef:
              name: go-demo-app-secret
              key: MY_SECRET
