apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-demo-app
  template:
    metadata:
      labels:
        app: go-demo-app
    spec:
      containers:
      - name: go-demo-app
        image: denvasyliev/go-demo-app:v1.0.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-demo-app-svc
spec:
  type: ClusterIP
  selector:
    app: go-demo-app
  ports:
  - port: 80
    targetPort: 8080
